"""pgloader .load file generation for MSSQL/MySQL → Snowflake Postgres."""
from __future__ import annotations

import configparser
import sys
from pathlib import Path


# ---------------------------------------------------------------------------
# pgloader .load file templates
# ---------------------------------------------------------------------------

MSSQL_TEMPLATE = """\
-- Generated by spgloader
-- Source: MS SQL Server {source_host}:{source_port}/{source_db}
-- Target: Snowflake Postgres ({target_service})

LOAD DATABASE
     FROM mssql://{source_user}:${{SOURCE_PASSWORD}}@{source_host}:{source_port}/{source_db}
     INTO {target_dsn}

WITH include drop,
     create tables,
     create indexes,
     reset sequences,
     foreign keys,
     downcase identifiers

CAST type uniqueidentifier  to uuid    using remove-null-from-string,
     type bit               to boolean using mssql-bit-to-boolean,
     type tinyint           to smallint,
     type float             to float,
     type money             to numeric using remove-null-from-string,
     type smallmoney        to numeric using remove-null-from-string,
     type datetime          to timestamptz,
     type datetime2         to timestamptz,
     type datetimeoffset    to timestamptz,
     type smalldatetime     to timestamp,
     type date              to date,
     type time              to time,
     type nvarchar          to text drop typemod,
     type varchar           to text drop typemod,
     type nchar             to text drop typemod,
     type char              to text drop typemod,
     type ntext             to text,
     type text              to text,
     type sysname           to text drop typemod,
     type xml               to text,
     type image             to bytea,
     type varbinary         to bytea

SET work_mem to '512MB',
    maintenance_work_mem to '1GB'

BEFORE LOAD DO
  $$ SET client_min_messages TO WARNING; $$,
  $$ CREATE SCHEMA IF NOT EXISTS dbo; $$;
"""

MYSQL_TEMPLATE = """\
-- Generated by spgloader
-- Source: MySQL {source_host}:{source_port}/{source_db}
-- Target: Snowflake Postgres ({target_service})

LOAD DATABASE
     FROM mysql://{source_user}:${{SOURCE_PASSWORD}}@{source_host}:{source_port}/{source_db}
     INTO {target_dsn}

WITH include drop,
     create tables,
     create indexes,
     reset sequences,
     foreign keys,
     downcase identifiers,
     no ssl cert verification,
     workers = 4, concurrency = 1

CAST type tinyint(1)   to boolean drop typemod,
     type bit          to boolean,
     type datetime     to timestamptz,
     type timestamp    to timestamptz,
     type date         to date,
     type time         to time,
     type year         to integer,
     type enum         to text,
     type set          to text,
     type json         to jsonb,
     type longtext     to text,
     type mediumtext   to text,
     type tinytext     to text,
     type longblob     to bytea,
     type mediumblob   to bytea,
     type tinyblob     to bytea

SET work_mem to '256MB',
    maintenance_work_mem to '512MB'

BEFORE LOAD DO
  $$ SET client_min_messages TO WARNING; $$;
"""


def build_target_dsn(service_name: str) -> str:
    """Read ~/.pg_service.conf + ~/.pgpass to build a DSN for pgloader."""
    service_file = Path.home() / ".pg_service.conf"
    if not service_file.exists():
        print("Error: ~/.pg_service.conf not found. Run pg_connect.py --list.", file=sys.stderr)
        sys.exit(1)

    cfg = configparser.ConfigParser()
    cfg.read(service_file)
    if service_name not in cfg:
        print(f"Error: service '{service_name}' not in ~/.pg_service.conf. "
              f"Available: {cfg.sections()}", file=sys.stderr)
        sys.exit(1)

    svc = cfg[service_name]
    host = svc.get("host", "")
    port = svc.get("port", "5432")
    dbname = svc.get("dbname", "postgres")
    user = svc.get("user", "snowflake_admin")
    sslmode = svc.get("sslmode", "require")
    password = _lookup_pgpass(host, port, dbname, user) or ""
    if not password:
        print(f"Warning: no password in ~/.pgpass for '{service_name}'. "
              f"Run pg_connect.py --reset --instance-name {service_name}.", file=sys.stderr)
    return f"postgresql://{user}:{password}@{host}:{port}/{dbname}?sslmode={sslmode}"


def _lookup_pgpass(host: str, port: str, dbname: str, user: str) -> str | None:
    pgpass = Path.home() / ".pgpass"
    if not pgpass.exists():
        return None
    for line in pgpass.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split(":")
        if len(parts) < 5:
            continue
        p_host, p_port, p_db, p_user = parts[:4]
        p_pass = ":".join(parts[4:])
        if all(f == "*" or f == a for f, a in [(p_host, host), (p_port, port), (p_db, dbname), (p_user, user)]):
            return p_pass
    return None


def generate_config(
    source_type: str,
    source_host: str,
    source_port: int,
    source_db: str,
    source_user: str,
    target_service: str,
) -> str:
    """Return the rendered pgloader .load file content."""
    target_dsn = build_target_dsn(target_service)
    template = MSSQL_TEMPLATE if source_type == "mssql" else MYSQL_TEMPLATE
    return template.format(
        source_host=source_host,
        source_port=source_port,
        source_db=source_db,
        source_user=source_user,
        target_service=target_service,
        target_dsn=target_dsn,
    )
